/* Generated by Cython 0.29.33 */

#ifndef __PYX_HAVE__pym
#define __PYX_HAVE__pym

#include "Python.h"

#ifndef __PYX_HAVE_API__pym

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C int python_handle_request(pam_handle_t *, int, int, char const **, char *);

#endif /* !__PYX_HAVE_API__pym */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initpym(void);
#else
PyMODINIT_FUNC PyInit_pym(void);
#endif

#endif /* !__PYX_HAVE__pym */
