/* Generated by Cython 0.29.24 */

#ifndef __PYX_HAVE__pam
#define __PYX_HAVE__pam

#include "Python.h"

#ifndef __PYX_HAVE_API__pam

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C void pam_module_init(char *);
__PYX_EXTERN_C void process_handle(pam_handle_t *);

#endif /* !__PYX_HAVE_API__pam */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initpam(void);
#else
PyMODINIT_FUNC PyInit_pam(void);
#endif

#endif /* !__PYX_HAVE__pam */
