/* Generated by Cython 3.0.0b2 */

#ifndef __PYX_HAVE__pym
#define __PYX_HAVE__pym

#include "Python.h"

#ifndef __PYX_HAVE_API__pym

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C void print_hello(void);

#endif /* !__PYX_HAVE_API__pym */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initpym(void);
#else
/* WARNING: Use PyImport_AppendInittab("pym", PyInit_pym) instead of calling PyInit_pym directly from Python 3.5 */
PyMODINIT_FUNC PyInit_pym(void);

#if PY_VERSION_HEX >= 0x03050000 && (defined(__GNUC__) || defined(__clang__) || defined(_MSC_VER) || (defined(__cplusplus) && __cplusplus >= 201402L))
#if defined(__cplusplus) && __cplusplus >= 201402L
[[deprecated("Use PyImport_AppendInittab(\"pym\", PyInit_pym) instead of calling PyInit_pym directly.")]] inline
#elif defined(__GNUC__) || defined(__clang__)
__attribute__ ((__deprecated__("Use PyImport_AppendInittab(\"pym\", PyInit_pym) instead of calling PyInit_pym directly."), __unused__)) __inline__
#elif defined(_MSC_VER)
__declspec(deprecated("Use PyImport_AppendInittab(\"pym\", PyInit_pym) instead of calling PyInit_pym directly.")) __inline
#endif
static PyObject* __PYX_WARN_IF_PyInit_pym_INIT_CALLED(PyObject* res) {
  return res;
}
#define PyInit_pym() __PYX_WARN_IF_PyInit_pym_INIT_CALLED(PyInit_pym())
#endif
#endif

#endif /* !__PYX_HAVE__pym */
